### ISSUE TITLE
Paper URL has SSL problems

### ISSUE THREAD

**Issue by kylecordes** [joneshf/elm-comonad#1]
This link from the README:

https://functorial.com/the-future-is-comonadic/main.pdf

produces errors in the browser. It appears this is an attempt at a custom URL for a file served by Github, but without SSL set up.

Easiest fix is probably to just replace this URL with one that points to the real location without the custom (non-working) domain name.

**Comment by joneshf** [comment]
Sorry about that. everything is an HTTPS link on this computer :). Will "fix" it.
